"""fix_schema

Revision ID: 32c606aa4e7b
Revises: 768e9d0e12d8
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c606aa4e7b'
down_revision = '768e9d0e12d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if amenities column exists before adding it
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('property')]
    
    if 'amenities' not in columns:
        op.add_column('property', sa.Column('amenities', sa.Text(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'amenities')
    # ### end Alembic commands ###