"""Add gender and birthdate to User

Revision ID: 35866e24c7f0
Revises: a9c62ab9f1d1
Create Date: 2025-11-14 04:09:49.440964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35866e24c7f0'
down_revision = 'a9c62ab9f1d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('birthdate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('birthdate')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
