"""Add slots column to Property

Revision ID: a9c62ab9f1d1
Revises: ea808dffecc7
Create Date: 2025-11-09 02:54:05.789809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9c62ab9f1d1'
down_revision = 'ea808dffecc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slots', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('slots')

    # ### end Alembic commands ###
